cdata = {
    TITLE      = _('SCRIPT CONFIGURATOR by pet333r'),

    ENABLE_SCRIPT_TITLE = _('Turn ON to edit Config.lua file'),
    ENABLE_SCRIPT_TITLE_TOOLTIP = _('Enable to be able to edit the settings file'),

    NETWORK_PORTS_TITLE = ('Network ports:'),
    NETWORK_PORTS_TITLE_TOOLTIP = (''),

    NETWORK_PORTS_SEND = _('Send:'),
    NETWORK_PORTS_SEND_TOOLTIP = _(''),
    NETWORK_PORTS_SEND_EDIT = _(''),
    NETWORK_PORTS_SEND_EDIT_TOOLTIP = _('The port on which data is sent to the device'),
    NETWORK_PORTS_SEND_EDIT_DEFAULT = _('default: 5160'),
    NETWORK_PORTS_SEND_EDIT_DEFAULT_TOOLTIP = _('default: 5160'),

    NETWORK_PORTS_RECV = _('Receive:'),
    NETWORK_PORTS_RECV_TOOLTIP = _(''),
    NETWORK_PORTS_RECV_EDIT = _(''),
    NETWORK_PORTS_RECV_EDIT_TOOLTIP = _('Port where data is received in DCS World'),
    NETWORK_PORTS_RECV_EDIT_DEFAULT = _('default: 25070'),
    NETWORK_PORTS_RECV_EDIT_DEFAULT_TOOLTIP = _('default: 25070'),

    MULTIAPP_TTITLE = _('Configuration for multiple applications on same device:'),
    MULTIAPP_TITLE_TOOLTIP = _(''),
    MULTIAPP_ENABLED = _('Multi app'),
    MULTIAPP_ENABLED_TOOLTIP = _('Turn this option on when you want to use DCS UFC & DCS Nav on the same device simitouosly'),

    DEVICES_TITLE = _('Your devices IP\'s (tablet / phone)'),
    DEVICES_TITLE_TOOLTIP = _(''),

    DEVICE_EDIT_TOOLTIP = _('The device\'s (tablet / phone) IP address in your local network'),
    DEVICE_ENABLED_TOOLTIP = _('Send data to this device'),

    DEVICE1_ENABLED = _('Device #1'),
    DEVICE2_ENABLED = _('Device #2'),
    DEVICE3_ENABLED = _('Device #3'),
    DEVICE4_ENABLED = _('Device #4'),

    STREAMDECK_TITLE = _('Configuration for StreamDeck'),
    STREAMDECK_TITLE_TOOLTIP = _(''),
    STREAMDECK_ENABLED = _('StreamDeck'),
    STREAMDECK_ENABLED_TOOLTIP = _('Enable if you want to send values to StreamDeck'),
    STREAMDECK_IP = _('IP:'),
    STREAMDECK_IP_TOOLTIP = _(''),
    STREAMDECK_EDIT = _(''),
    STREAMDECK_EDIT_TOOLTIP = _('Set the PC IP with StreamDeck connected (default same PC: 127.0.0.1)'),
    STREAMDECK_IP_DEFAULT = _('default: 127.0.0.1'),
    STREAMDECK_IP_DEFAULT_TOOLTIP = _('default: 127.0.0.1'),
    STREAMDECK_PORT = _('Port:'),
    STREAMDECK_PORT_TOOLTIP = _(''),
    STREAMDECK_PORT_EDIT = _(''),
    STREAMDECK_PORT_EDIT_TOOLTIP = _('Set the port for sending data to StreamDeck (default: 1725)'),
    STREAMDECK_PORT_DEFAULT = _('default: 1725'),
    STREAMDECK_PORT_DEFAULT_TOOLTIP = _(''),
    STREAMDECK_WRITE_NAVFILE = _('Write navigation data to file (KML & CSV)'),
    STREAMDECK_WRITE_NAVFILE_TOOLTIP = _(''),
    STREAMDECK_WRITE_NAVFILE_ENABLED = _('Write to file'),
    STREAMDECK_WRITE_NAVFILE_ENABLED_TOOLTIP = _('Enable the option of saving data to CSV & KML files (files will be saved in the \'Logs\' folder)'),

    TIPS1 = _('TIPS'),
    TIPS2 = _('It is not necessary to turn off additional devices if you do not have them (they will simply be ignored)'),
    TIPS3 = _('Never set the same IP address for several devices'),
    TIPS4 = _('To check the IP of an Android device: go to \'Settings\' > \'WiFi\' (Network) > connected network properties (it may differ depending on the Android system or the system overlay)'),
    
    BTN_PCIP = _('PC IP'),
    BTN_PCIP_TOOLTIP = _('Check your PC\'s local IP address'),
    BTN_SAVE = _('SAVE'),
    BTN_SAVE_TOOLTIP = _('Save current configuration to Config.lua file in script folder'),
    BTN_UPDATE = _('UPDATE'),
    BTN_UPDATE_TOOLTIP = _('Update the script files'),

    SCRIPT_INSTALLED = _('script installed:'),
    SCRIPT_INSTALLED_TOOLTIP = _('Script installed on your PC'),
    SCRIPT_AVAIBLE = _('update avaible:'),
}